// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyqimnqycplllzyxxmim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5cWltbnF5Y3BsbGx6eXh4bWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzQzMjcsImV4cCI6MjA2NjcxMDMyN30.DaevNXOUW9WA5bEzIxieb4cbmM49iodii7V4pRflXss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);